### ISSUE TITLE
[Suggestion/Feature request] CTRL+mine should allow you to break tile entities

### ISSUE THREAD

**Issue by KnyteGaming** [Direwolf20-MC/MiningGadgets#66] opened 2020-03-18 22:23 UTC
The mining gadget is an amazing tool and makes 1.15 super fun. But I’d love if I didn’t have to carry a pick around just for the purpose of moving tile entities. 

CTRL+mine could also be used as a quick toggle for the precision mode so you don’t have to open the GUI to switch back and forth.

**Comment by MichaelHillcox** [comment] 2020-03-19 15:10
@Direwolf20-MC

**Comment by Direwolf20-MC** [comment] 2020-03-19 15:37
The problem is the render. The 'block shrink' effect is a tile entity, so we'd need to store the current tile data, convert it to our tile, try to render the original tile (tricky) and then if you don't complete the break, it need to restore the original tile and tile data.

Unfortunately thats a LOT of complexity. I'm not saying its impossible, but it would be tricky and probably cause issues with some mods. 

I'd love to add it, but I think for now I have to pass.  Unless we decided to just have it insta-break TE's and not do any rendering and use the vanilla break block mechanic. I'll consider that option for now, but closing this for the time being.

**Closed by Direwolf20-MC** 2020-03-19 15:37 UTC
