### ISSUE TITLE
Rendering issue when running and shooting laser

### ISSUE THREAD

**Issue by TheAGamePlayer** [Direwolf20-MC/MiningGadgets#26] opened 2019-11-21 18:44 UTC
Just a funny little issue I stumbled upon :)
![2019-11-21_02 01 37](https://user-images.githubusercontent.com/58047374/69366621-93349a00-0c4b-11ea-967a-78ab28253fe6.png)
(notice how the laser doesn't quite line up with the tip of the gadget)

**Comment by Direwolf20-MC** [comment] 2019-11-21 18:58
That’s caused by the fov change. Same if you adjust the fov slider in options. I need to find a way to detect and correct that :)

**Comment by TheAGamePlayer** [comment] 2019-11-21 19:05
things I'd think of:
1) be lazy and make laser particle bursts instead of a continuous beam
2) store the FOV as a variable and use the variable to translate the laser to the correct position (I believe you can find the value by looking at the code for the speed potion or running in general)

**Comment by MichaelHillcox** [comment] 2019-12-12 18:55
@Direwolf20-MC There is a player.getFovModifier which will return a 1.x value for different types of modifiers. Upon this you can also get the players Fov from `Minecraft.getInstance().gameSettings.fov`

**Comment by MichaelHillcox** [comment] 2020-02-20 15:55
Will be fixed on 1.15 (and 1.14 if I backport)

**Closed** 2020-03-23 18:51 UTC
Labels: 1.14.x, 1.15.x, bug, investigate
