### ISSUE TITLE
Mining gadget Seems to ignore mining Fatigue from Elder Guardians

### ISSUE THREAD

**Issue by russrulz** [Direwolf20-MC/MiningGadgets#37] opened 2019-12-07 23:58 UTC
When i tryed to use mining gadget on the water temple after being hit with the debuff i expected it to take forever to break a block however it broke the block almost instantly as if i was not debuffed

Mining gadget had effecincy 5 upgrade silktouch upgrade magnet upgrade torch upgrade silktouch upgreade range upgrade and 3x3 upgrade

**Comment by russrulz** [comment] 2019-12-08 00:35
mininggadgets-1.2.3.jar

**Comment by MichaelHillcox** [comment] 2019-12-08 19:14
Seems likely, we've not taking that into consideration.

**Comment by MichaelHillcox** [comment] 2021-04-16 17:53
Fixed soon, it'll be in the next release, also duplicate of #135

**Closed by MichaelHillcox** 2021-04-16 17:53 UTC
Labels: awaiting release, enhancement, investigate, priority: low
