### ISSUE TITLE
Flux Network Wireless Energy Compatibility 1.18.2

### ISSUE THREAD

**Issue by Karma-Fox** [Direwolf20-MC/MiningGadgets#183] opened 2022-06-21 10:57 UTC
Using FluxNetworks-1.18.2-7.0.2.3.jar with working wireless charging network but mining laser is not accepting said energy. All other mod items are charging just fine.

Using Direwolf20 1.18.2 1.5.1 modpack with FluxNetworks added. No errors being reported in log.

EDIT:

This is a tip for anyone else whom may run into this same issue. Until such time as the mining laser is made compatible with flux net wireless charging, having a Flux Capacitor in your charm slot works. The wireless network will charge the flux capacitor while the flux capacitor charges the mining laser.

**Comment by MrV0DkAa** [comment] 2022-08-08 20:28
I'm playing in ATM6 1.16.5 Version 1.8.27 and having the same issue. I already did that with the Flux capacitor but when the Flux Capacitor got full, it doesn't charge Mining gadget... Any tip/fix for that, please?? That's really strange cause I use that combo for a long long long time and never had that issue....

**Comment by Furious1964** [comment] 2023-07-18 11:03
Will this problem ever be fixed? I really hope someone can take a look at this problem.

**Comment by Rahmiel** [comment] 2023-11-06 11:36
To add clarity, and to not flood the issues tab, this has continued even into 1.20 (tested in the Direwolf20 1.20 pack). The issue is peculiar because the Mining Gadget DOES charge once, but once it is full it will not charge again from Wireless sources like Flux Networks, nor from Battery type objects in the inventory. The peculiar state of this expands when you realize that if ANYTHING else is charging, the Mining Gadget will also charge until that other thing is full.

**Comment by Direwolf20-MC** [comment] 2023-11-06 11:47
That’s weird because I haven’t seen this in my play through. I’ll look into it but I’ve been charging the mining gadget with flux networks in my let’s play for weeks without issue. Wonder if there’s some other thing at play here.

**Comment by Anoyomouse** [comment] 2023-11-09 14:19
@Direwolf20-MC This is a bug in 1.18, not 1.20 .. 1.20 is working great
This might be a bug with the capabilities system that was changed in the 1.18 MC, i picked this up and fixed it in my original size upgrade changes (and energy changes).

This should be fixed in 1.20+
Would it make sense to backport this fix to 1.18?

**Comment by JosephBlock** [comment] 2023-11-26 19:59
@Rahmiel Do you happen to have Bypass Limit  enabled? I did some testing and can reproduce the issue with having Bypass Limit enabled on the controller. Seems to break when transfer limit is set to anything greater `int.MAX_VALUE`.

**Comment by MichaelHillcox** [comment] 2023-11-27 00:26
Feel free to backport @Anoyomouse could you link to the specific code changed to resolve this for newer versions?

**Comment by Anoyomouse** [comment] 2023-11-27 08:52
@MichaelHillcox It's basically when I updated the mod from using CapabilityEnergy -> ForgeCapabilities and you updated it for 1.19 -> https://github.com/Direwolf20-MC/MiningGadgets/blame/7edae79fe0a6fdccc47eb295f4ef82a536a159c0/src/main/java/com/direwolf20/mininggadgets/common/capabilities/CapabilityEnergyProvider.java#L28 (and all the references to ForgeCapabilities)

**Comment by Direwolf20-MC** [comment] 2024-08-03 20:01
Please re-open if this is an issue still in 1.21

**Closed by Direwolf20-MC** 2024-08-03 20:01 UTC
