### ISSUE TITLE
Mining blocks get stuck in animation and temporarily become un-mineable

### ISSUE THREAD

**Issue by IdealIdeas** [Direwolf20-MC/MiningGadgets#158] opened 2021-08-02 23:17 UTC
Modpack: Enigmatica 6
No Optifine, no extra mods.

Sometimes while mining, usually in diagonals, blocks will get stuck mid animation and become un-mineable for a short period of time.

**Comment by XXXJetfireXXX** [comment] 2021-08-23 18:33
Can confirm, I have the same problem from time to time. Especially in 3x3 mode when you're moving your cursor around.

**Comment by XXXJetfireXXX** [comment] 2021-08-25 07:34
Looks like it's a duplicate of https://github.com/Direwolf20-MC/MiningGadgets/issues/150

**Comment by Direwolf20-MC** [comment] 2024-08-03 20:03
Please re-open if this is an issue still in 1.21

**Closed by Direwolf20-MC** 2024-08-03 20:03 UTC
